noms_colonnes_sm = [
    'LOG_TIME','SP_ID','MSG_TYPE', 'MSG_MODE', 'MSG_STATUS', 'SM_ERROR', 'A_ADDR',
    'B_ADDR', 'A_IMSI', 'B_IMSI', 'A_AIM_NAIME', 'B_AIM_NAIME',
    'A_NETWORK_TYPE', 'B_NETWORK_TYPE', 'NR_DEL_ATT', 'MAP_ERROR', 'MAP_CAUSE',
    'SUBMIT_TIME', 'DELIVERY_TIME', 'MSG_ID'
]

noms_colonnes_sip = [
    'LOG_TIME', 'SIGNAL_OPER_TYPE', 'SIGNAL_TYPE', 'A_ADDR', 'B_ADDR',
    'MSG_ID', 'B_IMSI', 'B_EMEI', 'A_SC', 'B_SC',
    'S_ADDR', 'D_ADDR', 'CONTACT_REG_STATE', 'CONTACT_REG_EVENT', 'MSG_FLAGS',
    'DETECT_FLAGS', 'SIP_RESP_CODE', 'UPLI'
]

noms_colonnes_map = [
    'LOG_TIME', 'SP_ID', 'MSG_ID','MAP_OPER_TYPE', 'A_ADDR', 'B_ADDR',
     'A_IMSI','B_IMSI', 'MAP_A_IMSI', 'MAP_B_IMSI', 'S_CGPA','D_CDPA','B_HLR_CGPA','B_HLR_MAP_ERROR'
    'MAP_ERROR', 'MAP_CAUSE', 'MSG_FLAGS', 'D_CGPA', 'A_HLR_CGPA', 'A_HLR_MAP_ERROR','A_SC','B_SC',
    'HLR_MODIF_REQ','ODB','REQ_SUBS_INFO','SIGNAL_TYPE'
]
