export const nomsColonnesSM = [
  {
    title: "LOG_TIME",
    dataIndex: "LOG_TIME",
    key: "LOG_TIME",
  },
  {
    title: "SP_ID",
    dataIndex: "SP_ID",
    key: "SP_ID",
  },
  {
    title: "MSG_TYPE",
    dataIndex: "MSG_TYPE",
    key: "MSG_TYPE",
  },
  {
    title: "MSG_MODE",
    dataIndex: "MSG_MODE",
    key: "MSG_MODE",
  },
  {
    title: "MSG_STATUS",
    dataIndex: "MSG_STATUS",
    key: "MSG_STATUS",
  },
  {
    title: "SM_ERROR",
    dataIndex: "SM_ERROR",
    key: "SM_ERROR",
  },
  {
    title: "A_ADDR",
    dataIndex: "A_ADDR",
    key: "A_ADDR",
  },
  {
    title: "B_ADDR",
    dataIndex: "B_ADDR",
    key: "B_ADDR",
  },
  {
    title: "A_IMSI",
    dataIndex: "A_IMSI",
    key: "A_IMSI",
  },
  {
    title: "B_IMSI",
    dataIndex: "B_IMSI",
    key: "B_IMSI",
  },
  {
    title: "A_AIM_NAIME",
    dataIndex: "A_AIM_NAIME",
    key: "A_AIM_NAIME",
  },
  {
    title: "B_AIM_NAIME",
    dataIndex: "B_AIM_NAIME",
    key: "B_AIM_NAIME",
  },
  {
    title: "A_NETWORK_TYPE",
    dataIndex: "A_NETWORK_TYPE",
    key: "A_NETWORK_TYPE",
  },
  {
    title: "B_NETWORK_TYPE",
    dataIndex: "B_NETWORK_TYPE",
    key: "B_NETWORK_TYPE",
  },
  {
    title: "NR_DEL_ATT",
    dataIndex: "NR_DEL_ATT",
    key: "NR_DEL_ATT",
  },
  {
    title: "MAP_ERROR",
    dataIndex: "MAP_ERROR",
    key: "MAP_ERROR",
  },
  {
    title: "MAP_CAUSE",
    dataIndex: "MAP_CAUSE",
    key: "MAP_CAUSE",
  },
  {
    title: "SUBMIT_TIME",
    dataIndex: "SUBMIT_TIME",
    key: "SUBMIT_TIME",
  },
  {
    title: "DELIVERY_TIME",
    dataIndex: "DELIVERY_TIME",
    key: "DELIVERY_TIME",
  },
  {
    title: "MSG_ID",
    dataIndex: "MSG_ID",
    key: "MSG_ID",
  },
];

export const nomsColonnesSIP = [
  { title: "LOG_TIME", dataIndex: "LOG_TIME", key: "LOG_TIME" },
  { title: "SIGNAL_OPER_TYPE", dataIndex: "SIGNAL_OPER_TYPE", key: "SIGNAL_OPER_TYPE" },
  { title: "SIGNAL_TYPE", dataIndex: "SIGNAL_TYPE", key: "SIGNAL_TYPE" },
  { title: "A_ADDR", dataIndex: "A_ADDR", key: "A_ADDR" },
  { title: "B_ADDR", dataIndex: "B_ADDR", key: "B_ADDR" },
  { title: "MSG_ID", dataIndex: "MSG_ID", key: "MSG_ID" },
  { title: "B_IMSI", dataIndex: "B_IMSI", key: "B_IMSI" },
  { title: "B_EMEI", dataIndex: "B_EMEI", key: "B_EMEI" },
  { title: "A_SC", dataIndex: "A_SC", key: "A_SC" },
  { title: "B_SC", dataIndex: "B_SC", key: "B_SC" },
  { title: "S_ADDR", dataIndex: "S_ADDR", key: "S_ADDR" },
  { title: "D_ADDR", dataIndex: "D_ADDR", key: "D_ADDR" },
  { title: "CONTACT_REG_STATE", dataIndex: "CONTACT_REG_STATE", key: "CONTACT_REG_STATE" },
  { title: "CONTACT_REG_EVENT", dataIndex: "CONTACT_REG_EVENT", key: "CONTACT_REG_EVENT" },
  { title: "MSG_FLAGS", dataIndex: "MSG_FLAGS", key: "MSG_FLAGS" },
  { title: "DETECT_FLAGS", dataIndex: "DETECT_FLAGS", key: "DETECT_FLAGS" },
  { title: "SIP_RESP_CODE", dataIndex: "SIP_RESP_CODE", key: "SIP_RESP_CODE" },
  { title: "UPLI", dataIndex: "UPLI", key: "UPLI" },
];


export const nomsColonnesMAP = [
  { title: "LOG_TIME", dataIndex: "LOG_TIME", key: "LOG_TIME" },
  { title: "SP_ID", dataIndex: "SP_ID", key: "SP_ID" },
  { title: "MSG_ID", dataIndex: "MSG_ID", key: "MSG_ID" },
  { title: "MAP_OPER_TYPE", dataIndex: "MAP_OPER_TYPE", key: "MAP_OPER_TYPE" },
  { title: "A_ADDR", dataIndex: "A_ADDR", key: "A_ADDR" },
  { title: "B_ADDR", dataIndex: "B_ADDR", key: "B_ADDR" },
  { title: "A_IMSI", dataIndex: "A_IMSI", key: "A_IMSI" },
  { title: "B_IMSI", dataIndex: "B_IMSI", key: "B_IMSI" },
  { title: "MAP_A_IMSI", dataIndex: "MAP_A_IMSI", key: "MAP_A_IMSI" },
  { title: "MAP_B_IMSI", dataIndex: "MAP_B_IMSI", key: "MAP_B_IMSI" },
  { title: "S_CGPA", dataIndex: "S_CGPA", key: "S_CGPA" },
  { title: "D_CDPA", dataIndex: "D_CDPA", key: "D_CDPA" },
  { title: "B_HLR_CGPA", dataIndex: "B_HLR_CGPA", key: "B_HLR_CGPA" },
  { title: "B_HLR_MAP_ERROR", dataIndex: "B_HLR_MAP_ERROR", key: "B_HLR_MAP_ERROR" },
  { title: "MAP_ERROR", dataIndex: "MAP_ERROR", key: "MAP_ERROR" },
  { title: "MAP_CAUSE", dataIndex: "MAP_CAUSE", key: "MAP_CAUSE" },
  { title: "MSG_FLAGS", dataIndex: "MSG_FLAGS", key: "MSG_FLAGS" },
  { title: "D_CGPA", dataIndex: "D_CGPA", key: "D_CGPA" },
  { title: "A_HLR_CGPA", dataIndex: "A_HLR_CGPA", key: "A_HLR_CGPA" },
  { title: "A_HLR_MAP_ERROR", dataIndex: "A_HLR_MAP_ERROR", key: "A_HLR_MAP_ERROR" },
  { title: "A_SC", dataIndex: "A_SC", key: "A_SC" },
  { title: "B_SC", dataIndex: "B_SC", key: "B_SC" },
  { title: "HLR_MODIF_REQ", dataIndex: "HLR_MODIF_REQ", key: "HLR_MODIF_REQ" },
  { title: "ODB", dataIndex: "ODB", key: "ODB" },
  { title: "REQ_SUBS_INFO", dataIndex: "REQ_SUBS_INFO", key: "REQ_SUBS_INFO" },
  { title: "SIGNAL_TYPE", dataIndex: "SIGNAL_TYPE", key: "SIGNAL_TYPE" },
];
